name: Install Solr 9 for SAP Commerce Cloud

on:
  workflow_dispatch:
env: 
  SOLR_VERSION: 9.5.0

jobs:
  setup-solr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
          mvn -version  # Verify Maven installation

      - name: Install Solr ${{ vars.SOLR_VERSION }}
        id: install_solr_pkg
        run: |
          echo "Install Solr ${{ env.SOLR_VERSION }}"
          mvn -v install:install-file -DgroupId=org.apache.solr -DartifactId=solr -Dversion=${{ env.SOLR_VERSION }} -Dpackaging=zip -Dfile=solr-${{ env.SOLR_VERSION }}.zip
          mvn dependency:tree

      - name: Install Solr ${{ vars.SOLR_VERSION }}
        run: |
          mvn install:install-file -DgroupId=org.apache.solr -DartifactId=solr -Dversion=${{ env.SOLR_VERSION }} -Dpackaging=zip -Dfile=solr-${{ env.SOLR_VERSION }}.zip
          mvn dependencies:true
