name: Install Solr 9 for SAP Commerce Cloud

on:
  workflow_dispatch:

jobs:
  setup-solr:
    runs-on: ubuntu-latest

    steps:
     # - name: Checkout the code
     #   uses: actions/checkout@v3

      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
          mvn -version  # Verify Maven installation

      - name: Download Solr ${{ vars.SOLR_VERSION }} Package
        run: |
          echo "Downloading Solr Package"
          curl -s -O "https://archive.apache.org/dist/solr/solr/${{ env.SOLR_VERSION }}/solr-${{ env.SOLR_VERSION }}.tgz"
          tar xzf solr-${{ env.SOLR_VERSION }}.tgz
          zip -r -qq solr-${{ env.SOLR_VERSION }}.zip solr-${{ env.SOLR_VERSION }}

      - name: Install Solr ${{ vars.SOLR_VERSION }}
        run: |
          mvn install:install-file -DgroupId=org.apache.solr -DartifactId=solr -Dversion=${{ env.SOLR_VERSION }} -Dpackaging=zip -Dfile=solr-${{ env.SOLR_VERSION }}.zip
          mvn dependencies:true
