name: Install and Verify Solr 9 for SAP Commerce Cloud

on:
  workflow_dispatch:

env: 
  SOLR_VERSION: 9.5.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Git checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 1
          fetch-tags: true

      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

     # - name: Set solrserver.solr.server.version property
      #  run: |
       #   echo "solrserver.solr.server.version=${{ env.SOLR_VERSION }}" >> local.properties

      - name: Download Solr ${{ env.SOLR_VERSION }} Package
        id: download_solr_pkg
        run: |
          echo "Downloading Solr ${{ env.SOLR_VERSION }}"
          curl -s -O "https://archive.apache.org/dist/solr/solr/${{ env.SOLR_VERSION }}/solr-${{ env.SOLR_VERSION }}.tgz"

      - name: Extract and Repackage Solr
        id: repackage_solr
        run: |
          echo "Extracting Solr ${{ env.SOLR_VERSION }}"
          tar -xzf solr-${{ env.SOLR_VERSION }}.tgz
          echo "Repackaging Solr ${{ env.SOLR_VERSION }} as ZIP"
          zip -r solr-${{ env.SOLR_VERSION }}.zip solr-${{ env.SOLR_VERSION }}


      - name: Install Solr ${{ env.SOLR_VERSION }} to Local Maven Repository
        id: install_solr_pkg
        run: |
          echo "Installing Solr ${{ env.SOLR_VERSION }} to Maven repository"
          mvn install:install-file -DgroupId=org.apache.solr -DartifactId=solr -Dversion=${{ env.SOLR_VERSION }} -Dpackaging=zip -Dfile=solr-${{ env.SOLR_VERSION }}.zip
          mvn dependency:tree

